### ISSUE TITLE
Telegram bot to report cryptostore errors

### ISSUE THREAD

**Issue by yohplala** [bmoscon/cryptostore#115]
Hi,

Having setup my 'cryptostore server', I connect from time to time to check if everything is running good, mostly by having a look at `cryptostore.log`and `feedhandler.log`.

Instead of taking time to ssh'ing this server, we could have a cryptostore plug-in forwarding the error messages reported, possibly to `Telegram`, and I guess some professional software engineers here around might want to use `Slack` for that ;).

Possibly only an extract of the error message is enough. The goal is to be informed that something is wrong, or possibly wrong, not to solve it from Telegram, so no need to have lot of details.

Also, in addition to forward extract of errrors reported in `cryptostore.log` and `feedhandler.log` , this plug-in would check that all cryptostore related processes are still running, using their PID.
(this to be able to spot if the process has been killed by a system supervisor or not, just like the out of memory problem I had, and for which I simply had no error message from cryptostore because it was simply killed by the system supervisor)

At the moment, I am just issuing the idea.
I have myself prioritizing the development of other features in cryptofeed .:)
If anyone wants to get started, please, you are welcome 👍 .

To be noticed, `freqtrade`, an open source project that I am at the moment tracking (crypto trading bot) features such a Telegram bot to forward status of on-going trades, AFAIK.
https://www.freqtrade.io/en/latest/telegram-usage/
(actually, I would say  that this is from this feature that I stole the idea :))
This might be a good starting point.

Bests

**Comment by bmoscon** [comment]
@yohplala seems like a good ask - there is a ticket on the cryptofeed side to provide callbacks with performance metrics, could probably expose those here
