### ISSUE TITLE
Need a requirements.txt file with fixed library versions

### ISSUE THREAD

**Issue by iamkucuk** [bmoscon/cryptostore#131]
**Is your feature request related to a problem? Please describe.**
This is known to be a best practice to choose a specific version of a library. It will prevent unwanted breaks, and lets us assume that everyone is on the same page.

**Describe the solution you'd like**
Uhhmmm, a requrements.txt file?

**Describe alternatives you've considered**
Updating the docker file as well, and maybe an environment yaml for a conda environment?

**Additional context**
An example headache is within the PR #130

**Comment by yohplala** [comment]
@iamkucuk 
I am not an expert of the topic, but it seems to me that lib version is managed in setup.y (starting line 37) except that in our case, pyarrow has no min version.
Bests,

**Comment by iamkucuk** [comment]
@yohplala 
Setup file indeed includes some versioning, but it's not the best thing that using setup.py with a development environment.

**Comment by bmoscon** [comment]
I'm fine with a requirements file, but I won't accept pinning versions. At most things can specify the minimum required version, but there is no reason to pin something and prevent/disallow an upgrade.

**Comment by bmoscon** [comment]
I added the file. I'd argue setup.py is better because it allows you to install all the optional dependencies. using requirements.txt will not install enough dependencies to allow you to use the software

**Comment by iamkucuk** [comment]
> I'm fine with a requirements file, but I won't accept pinning versions. At most things can specify the minimum required version, but there is no reason to pin something and prevent/disallow an upgrade.

I would like to oppose that one because using the latest version of software may require constant supervision, as some dependencies may have breaking changes as they upgrade. PyArrow upgrade was a good example for it, and we already experienced a breaking change. I often face this issue with the dependencies I don't specify the version. It's a known best practice within conda, and pypi packages. They usually are using a pinned version of the dependency, instead of using the latest one.

**Comment by iamkucuk** [comment]
> I added the file. I'd argue setup.py is better because it allows you to install all the optional dependencies. using requirements.txt will not install enough dependencies to allow you to use the software

requirements.txt file is not for deploying and using the software, but is for developing it. It's really useful when you create (or replicate) your development environment. So when a developer wants to contribute the code base, but faces some issue, your first question will be "did you replicate the development environment".

**Comment by bmoscon** [comment]
if there is a breaking change, then we can update setup.py until said change was fixed. The breaking change you are referring to is with some new code, right?

**Comment by iamkucuk** [comment]
> 
> 
> if there is a breaking change, then we can update setup.py until said change was fixed. The breaking change you are referring to is with some new code, right?

Yes, it was with the PR I mentioned in the first post.
