### ISSUE TITLE
"Unauthorized for url" when connecting to Influx

### ISSUE THREAD

**Issue by jadaworth** [bmoscon/cryptostore#138]
Hey everyone, please excuse my ignorance, I am very new to using databases.

I am getting the following error when I try to run cryptostore with redis > influxdb. The redis part of the system seems to be working fine (I think).

> 2020-11-14 15:45:10,998 : INFO : Starting cryptostore
> 2020-11-14 15:45:10,998 : INFO : Cryptostore running on PID 30870
> 2020-11-14 15:45:11,000 : INFO : Spawner started
> 2020-11-14 15:45:11,001 : INFO : Spawner running on PID 30880
> 2020-11-14 15:45:11,002 : INFO : Aggregator started
> 2020-11-14 15:45:11,003 : INFO : Aggregator running on PID 30881
> 2020-11-14 15:45:11,003 : INFO : Cryptostore started
> 2020-11-14 15:45:11,011 : INFO : start: ['COINBASE'] stop: []
> 2020-11-14 15:45:11,012 : INFO : message: {"op": "start", "exchange": "COINBASE", "collector": {"retries": -1, "ticker": ["BTC-USD"]}, "config": {"cache": "redis", "redis": {"ip": "127.0.0.1", "port": 6379, "socket": null, "del_after_read": true, "retention_time": null, "start_flush": true}, "storage": ["influx"], "storage_retries": 5, "storage_retry_wait": 30, "influx": {"host": "http://127.0.0.1:8086", "db": "example", "create": false, "username": "influx_user", "password": "password1"}, "arctic": "mongodb://127.0.0.1", "storage_interval": 10}}
> 2020-11-14 15:45:11,013 : INFO : Starting {'op': 'start', 'exchange': 'COINBASE', 'collector': {'retries': -1, 'ticker': ['BTC-USD']}, 'config': {'cache': 'redis', 'redis': {'ip': '127.0.0.1', 'port': 6379, 'socket': None, 'del_after_read': True, 'retention_time': None, 'start_flush': True}, 'storage': ['influx'], 'storage_retries': 5, 'storage_retry_wait': 30, 'influx': {'host': 'http://127.0.0.1:8086', 'db': 'example', 'create': False, 'username': 'influx_user', 'password': 'password1'}, 'arctic': 'mongodb://127.0.0.1', 'storage_interval': 10}}
> 2020-11-14 15:45:11,015 : INFO : Collector for COINBASE running on PID 30883
> 2020-11-14 15:45:11,017 : INFO : Flushing cache
> 2020-11-14 15:45:11,020 : INFO : Reading COINBASE-ticker-BTC-USD
> 2020-11-14 15:45:11,020 : INFO : No data for COINBASE-ticker-BTC-USD
> 2020-11-14 15:45:21,021 : INFO : Reading COINBASE-ticker-BTC-USD
> 2020-11-14 15:45:21,021 : INFO : ticker-COINBASE-BTC-USD: Read 8 messages from Redis
> 2020-11-14 15:45:21,025 : ERROR : Aggregator running on PID 30881 died due to exception
> Traceback (most recent call last):
>   File "/home/ubuntu/.local/share/virtualenvs/cryptofeed-6hjDp-wh/lib/python3.8/site-packages/cryptostore/aggregator/aggregator.py", line 96, in loop
>     store.write(exchange, dtype, pair, time.time())
>   File "/home/ubuntu/.local/share/virtualenvs/cryptofeed-6hjDp-wh/lib/python3.8/site-packages/cryptostore/data/storage.py", line 37, in write
>     s.write(exchange, data_type, pair, timestamp)
>   File "/home/ubuntu/.local/share/virtualenvs/cryptofeed-6hjDp-wh/lib/python3.8/site-packages/cryptostore/data/influx.py", line 87, in write
>     r.raise_for_status()
>   File "/home/ubuntu/.local/share/virtualenvs/cryptofeed-6hjDp-wh/lib/python3.8/site-packages/requests/models.py", line 943, in raise_for_status
>     raise HTTPError(http_error_msg, response=self)
> requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: http://127.0.0.1:8086/write?db=example
> Task exception was never retrieved
> future: <Task finished name='Task-2' coro=<Aggregator.loop() done, defined at /home/ubuntu/.local/share/virtualenvs/cryptofeed-6hjDp-wh/lib/python3.8/site-packages/cryptostore/aggregator/aggregator.py:42> exception=HTTPError('401 Client Error: Unauthorized for url: http://127.0.0.1:8086/write?db=example')>
> Traceback (most recent call last):
>   File "/home/ubuntu/.local/share/virtualenvs/cryptofeed-6hjDp-wh/lib/python3.8/site-packages/cryptostore/aggregator/aggregator.py", line 96, in loop
>     store.write(exchange, dtype, pair, time.time())
>   File "/home/ubuntu/.local/share/virtualenvs/cryptofeed-6hjDp-wh/lib/python3.8/site-packages/cryptostore/data/storage.py", line 37, in write
>     s.write(exchange, data_type, pair, timestamp)
>   File "/home/ubuntu/.local/share/virtualenvs/cryptofeed-6hjDp-wh/lib/python3.8/site-packages/cryptostore/data/influx.py", line 87, in write
>     r.raise_for_status()
>   File "/home/ubuntu/.local/share/virtualenvs/cryptofeed-6hjDp-wh/lib/python3.8/site-packages/requests/models.py", line 943, in raise_for_status
>     raise HTTPError(http_error_msg, response=self)
> requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: http://127.0.0.1:8086/write?db=example

Maybe related: I am confused what the name of the influx database is supposed to be in the config.yaml file becasue when I setup the InfluxDB using their CLI I set up an organization name, bucket name, username, and password, but not a database name.

Thanks so much and please let me know if I should provide more info.

**Comment by bmoscon** [comment]
Can you use the latest code from github?

**Comment by jadaworth** [comment]
> Can you use the latest code from github?

Do you mean as opposed to the code installed with "pip3 install cryptostore"?

**Comment by bmoscon** [comment]
i updated what is in pypi, so you can install with pip now (you'll need a --upgrade if its already installed)

**Comment by jadaworth** [comment]
Thanks so much for your quick replies and for updating pypi. I rolled back InfluxDB to 1.8.3 from 2.0.1 and updated cryptostore with pip3...and now it is working! Not sure what did it, but given the fact that InfluxDB 2.0 apparently came out within the last few days and looks to have a substantially different interface, I wouldn't be surprised if InfluxDB 2.0 was a large part of the issue.

As an aside, thank you for writing such an amazing piece of software (cryptofeed and cryptostore). People pay big money for this quality of code, especially in the financial sector.

**Comment by bmoscon** [comment]
I'm thinking this is related to influx 2.0. The auth method differs in 1.x vs 2.x. Cryptofeed supports both, cryptostore does not (yet).

**Comment by bmoscon** [comment]
cryptostore supports influx 2.x+ only now, so marking this as closed
