### ISSUE TITLE
Any way to avoid huge feedhandler.log file size?

### ISSUE THREAD

**Issue by jadaworth** [bmoscon/cryptostore#142]
My current feedhandler.log is 1.3GB and crashes VS Code when I try to open it via ssh. This is part question: is there a way to avoid this by splitting the file after a certain size/time is reached? Part proposal: to split this log file into smaller ones?

**Comment by bmoscon** [comment]
feedhandler.log comes from cryptofeed. I've made a commit there to rotate log files every 10 mb, and to save 10 log files in total (so 100mb of log files). You'll need to upgrade cryptofeed manually to get this fix, or wait for it to be released to pypi
