### ISSUE TITLE
Book Build Example

### ISSUE THREAD

**Issue by jzay** [bmoscon/cryptostore#143]
I'm encountering issues try to test out the book built example. 

Is this a working example? It seems like something in the codebase changed the way the data is structured

**Comment by bmoscon** [comment]
fixed

**Comment by jzay** [comment]
It looks like it gets it right on the first few iterations but then the best Bid & Ask get increasingly further apart from on another. I know the spread isn't $20+ on Bitmex so I'm not sure what's calculating wrong

**Comment by bmoscon** [comment]
I've updated the example to use sorted dicts. Cryptofeed requires is, so it should be installed.

**Comment by bmoscon** [comment]
also, bitmex doesnt support sequence numbers of book checksums, so its not really possible to know if book data has been lost or not (barring seeing a crossed book)
