### ISSUE TITLE
Better example how to read data from Arctic?

### ISSUE THREAD

**Issue by piccolorio** [bmoscon/cryptostore#146]
I am using book_build.py as an example. Modified to use pandas==1.1.5 so that Arctic would work but still I am not able to read the data. Maybe a better example exists how to read the book, ticker, trades from Arctic?

(.venv) cryptostore$ python read_data.py 
cryptostore/.venv/lib/python3.8/site-packages/arctic/_util.py:6: FutureWarning: pandas.util.testing is deprecated. Use the functions in the public API at pandas.testing instead.
  from pandas.util.testing import assert_frame_equal
cryptostore/.venv/lib/python3.8/site-packages/arctic/store/_pandas_ndarray_store.py:6: FutureWarning: The Panel class is removed from pandas. Accessing it from the top-level namespace will also be removed in the next version
  from pandas import DataFrame, Series, Panel
Traceback (most recent call last):
  File "read_data.py", line 36, in <module>
    main()
  File "read_data.py", line 26, in main
    book[side][price] = size
KeyError: Timestamp('2021-01-06 05:05:22.782702446')

**Comment by bmoscon** [comment]
arctic has documentation: https://github.com/man-group/arctic/blob/master/docs/index.md
