### ISSUE TITLE
Replay from store

### ISSUE THREAD

**Issue by djdjoko** [bmoscon/cryptostore#157]
Is there any good example how to replay data from the cryptostore?

Particularly I am interested to have a replay functionality that can merge both live and historical data. Are there any plans on this or what would be the best starting point to implement this within cryptostore?

Thanks for the great project!

**Comment by bmoscon** [comment]
replaying data will vary by storage medium. For arctic, its pretty easy. You can query the data by whatever date range you want and it gives you a pandas dataframe. From there you can either iterate on it a row at a time (i.e. an update at a time) or in some other block
