### ISSUE TITLE
Missing Trade Detection

### ISSUE THREAD

**Issue by bmoscon** [bmoscon/cryptostore#16]

**Comment by kozy** [comment]
Maybe some sort of standardized heartbeat signal in redis for the feeds is good at first. That way you could know when to close candlesticks as well which is useful. Then when cryptostore detects an inconsistency you could pause the heartbeat, preventing possible finalizing of timeframes downstream, and continue after the missing trades have been downloaded. 

Thanks for the great software, a happy user :)
