### ISSUE TITLE
Weirdness in installing cryptostore with aiohttp 4.0.0a1

### ISSUE THREAD

**Issue by yohplala** [bmoscon/cryptostore#161]
Hi,
I re-installed cryptostore on a new machine.
I did not have aiohttp, so it fetched the last version, the 4.0.0a1.
Then setup checks dependency and refuses to ends correctly the install, telling me:

`error: aiohttp 4.0.0a1 is installed but aiohttp<4.0.0,>=3.7.1 is required by {'cryptofeed'}`

**Comment by yohplala** [comment]
Same with `idna`

`error: idna 3.1 is installed but idna<3,>=2.5 is required by {'requests'}`

**Comment by bmoscon** [comment]
see https://pypi.org/project/aiohttp/#history

3.7.3 is the latest, the 4.0 pre-release candidates are all from 2019. You may need to manually remove it
