### ISSUE TITLE
[Kraken] ValueError: Valid depths for Kraken are 10, 25, 100, 500 or 1000 - max_depth is not being set if not set in config

### ISSUE THREAD

**Issue by dirtyValera** [bmoscon/cryptostore#163]
**Describe the bug**
if max_depth is not set in config, it is not being set to default properly when exchange object is initialised

See line 30-32 in kraken.py: max_depth=1000 is not being passed downstream, it passes None instead

Even if I set max_depth in config for l2, the problem is still there if I also add ticker feed in config (since it also initialises Kraken object with empty max_depth)

**Trace**
https://pastebin.com/HbWRLmVd

**Config**
https://pastebin.com/qwM42JKA

**Operating System:**
 macOS

**Cryptofeed Version**
latest master

**Comment by dirtyValera** [comment]
Ping ping, is there any update? Still getting this issue

**Comment by dirtyValera** [comment]
Created PR with the fix https://github.com/bmoscon/cryptofeed/pull/428

**Comment by bmoscon** [comment]
fixed in cryptostore
