### ISSUE TITLE
[Parquete] Writing to parquete fails with "TypeError: not a path-like object"

### ISSUE THREAD

**Issue by dirtyValera** [bmoscon/cryptostore#166]
**Describe the bug**
Creating parquete file fails. Verified for Binance and Coinbase

**Trace**
https://pastebin.com/1kRCMpVe

**Config**
https://pastebin.com/47izWa69

**Operating System:**
macOS

**Cryptofeed Version**
latest master

**Comment by bmoscon** [comment]
you are missing this config param: https://github.com/bmoscon/cryptostore/blob/master/config.yaml#L129
