### ISSUE TITLE
[Parquete + Kafka] receipt_timestamp is bool for l2_book files

### ISSUE THREAD

**Issue by dirtyValera** [bmoscon/cryptostore#167]
**Describe the bug**
I'm trying to understand if I'm doing something wrong, but it seems like a bug to me. Parquete files for l2 books have receipt_timestamp as bool, and delta as double (with value of a timestamp). Could it be that these two are accidentally swapped? Please see links/screenshots

**File contents**
https://pastebin.com/EEKVAmZF

**File schema**
https://pastebin.com/fpvsV6N1

**Screenshots**
![image](https://user-images.githubusercontent.com/6611361/109382179-f18d0580-78ef-11eb-9d4f-69dd995ad3fa.png)

![image](https://user-images.githubusercontent.com/6611361/109382185-f487f600-78ef-11eb-85e4-69903ec12d06.png)

**Config**
https://pastebin.com/Yf6SjzkQ

**Comment by yohplala** [comment]
Hi @dirtyValera 
Using redis and parquet on my side, no trouble.
Would you mind testing redis?
This might then be due to Kafka.

![Capture d’écran de 2021-02-27 13-42-26](https://user-images.githubusercontent.com/13206058/109387448-cb706100-7901-11eb-95f2-9813f7a5410e.png)

**Comment by dirtyValera** [comment]
@yohplala, Redis seems to be working correctly. What could be the problem here? I thought parquet write logic was independent from the medium.

**Comment by yohplala** [comment]
Parquet is only an end of the process.
You are seeing this trouble with kafka + parquet, but it does not mean it would not appear with kafka + another storage.
Would be useful to know about the conbination of Kafka + Arctic for instance.

@bmoscon 
do you think you could give it a try?

**Comment by dirtyValera** [comment]
@yohplala, not directly related to the issue, but I have a question regarding timestamp field precision. It looks like the real value is truncated when being stored in parquete. If I subscribe to kafka topic I get higher precision. If I read parquete file with pandas and for example call diff() on the timestamp column I get zeroes. Is it a bug?

**Comment by yohplala** [comment]
Hi, please, could provide an example? I am not sure to understand.
On my side, timestamp is inferred by pyarrow library as a float64. Because of float64 type, it is possible that there is 'approximation' of value.
Then, up to you to convert it into a datetime64 through pandas indeed.
I don't know how is managed timestamp through Kafka.
Bests,

**Comment by dirtyValera** [comment]
Still able to reproduce

**Comment by bmoscon** [comment]
I'll try and reproduce this locally this week
