### ISSUE TITLE
Pulling data from COINBASE/BITFINEX/BITMEX gives timestamps from 1970

### ISSUE THREAD

**Issue by e-mulville** [bmoscon/cryptostore#17]
While the file names for the data from COINBASE/BITFINEX/BITMEX seems correct the 'timestamp' column in the dataframes returns 1970.

BINANCE using the same code has the correct timestamps.

**Comment by e-mulville** [comment]
Example timestamp from BITMEX: 1970-01-19 01:56:25.855891

**Comment by bmoscon** [comment]
@e-mulville can you confirm the storage type you are using?

**Comment by bmoscon** [comment]
this has been fixed (fix was in cryptofeed)
