### ISSUE TITLE
Anybody who can maintain an all supported config template file?

### ISSUE THREAD

**Issue by walter211** [bmoscon/cryptostore#171]
I am trying to deploy other exchange by using cryptostore, confuse about the config.

Hope someone can miantain a cryptostore supported config for all these exchange

**Comment by bmoscon** [comment]
Every exchange, every symbol, every data channel is unlikely to work on the average user's setup, so its not something I want to have in the codebase. People will see it, try it, and assume because its provided it should work, when it will likely not

**Comment by slidenerd** [comment]
I would be happy to help doing this but I would like to know a few things first

1. The list of symbols from whatever examples I have seen is hardcoded. How would you add a new pair to it tomorrow when some exchange adds a new pair
2. Some exchanges have a limit like you can get only X pairs per connection, does the library automatically manage this or does it have to be done manually?
3. How do you determine if you are overdoing it on a single instance? Let us say you were planning to run this on AWS? What would you do? Get a t3.micro for each exchange? How do you measure if you are underdoing it or overdoing it? CPU usage? If you are storing the tradebooks as it is on redis stream or redis backend, does it not count as an IO operation for the most part?
4. I am planning to build a trading terminal of sorts open to users hence my questions
