### ISSUE TITLE
Capped Collections

### ISSUE THREAD

**Issue by JamesKBowler** [bmoscon/cryptostore#172]
Hello, 
I have limited storage on the mongodb server and therfore I would like to set this application to make use of Capped Collections.
https://docs.mongodb.com/manual/core/capped-collections/

Is this possible?

Thanks

**Comment by bmoscon** [comment]
cryptostore doesnt support mongo - so the answer is no, its not supported. Anything is possible if someone spends the time implementing it, but its not something I'll be doing anytime soon

**Comment by JamesKBowler** [comment]
ok, that's confused me further because cryptostore is using Arctic which I guess use's mongo.
```
# arctic specific configuration options - the mongo URL
arctic: mongodb://127.0.0.1
```

**Comment by bmoscon** [comment]
Cryptostore supports arctic, and arctic uses mongo. Arctic does not support this collection type.

**Comment by JamesKBowler** [comment]
Thanks for clearing that up.
