### ISSUE TITLE
about the BITMEX confusion in config.yaml 

### ISSUE THREAD

**Issue by xiandong79** [bmoscon/cryptostore#174]
With the lastest commit in config.yaml, now the **XBTUSD** symbol from BITMEX has been changed to **BTC-USD**, however, in the comments, line 28 of config.yaml

```
# Trading pairs for all exchanges (except BitMEX, Deribit and other derivatives) follow the currency-quote format.
```

It would be confused to how to config the symbols from BITMEX. @bmoscon

**Comment by bmoscon** [comment]
updated
