### ISSUE TITLE
kafka callback in cryptostore collector wrongly labels kwargs 'bootstrap' as 'host'

### ISSUE THREAD

**Issue by qinghuangchan** [bmoscon/cryptostore#175]
**Describe the bug**

In `cryptostore/collector.py` line 77
`kwargs = {'host': self.config['kafka']['ip'], 'port': self.config['kafka']['port']}`

However, in `cryptofeed/backends/kafka.py`, the KafkaCallback expects
`def __init__(self, bootstrap='127.0.0.1', port=9092, key=None, numeric_type=float, **kwargs):`

**Cryptofeed Version**
Master

**Comment by bmoscon** [comment]
this has been fixed
