### ISSUE TITLE
Docker: Stop Cryptostore if Aggregator crashes

### ISSUE THREAD

**Issue by peske** [bmoscon/cryptostore#187]
First thanks for this piece of art!

I'm running Cryptostore in Kubernetes cluster (Docker image created by using your `Dockerfile`), and I have problem with the following behavior:

When Cryptostore process is started, it launches additional Aggregator process. For different reasons it may happen that Aggregator process crashes, but Cryptostore process continues to run as if everything is OK, keeping the Docker image _alive_, so that k8s is not aware that there's a problem. It would be much better if Cryptostore process also stops when Aggregator process crashes, so that Kubernetes can notice the problem and restart the pod. Also some other monitoring/alerting tools will be able to detect the problem and react.

My question (or feature request?) is: is it possible to somehow configure Cryptostore to exit if Aggregator crashes?

Thanks!

**Comment by bmoscon** [comment]
yes of course. It would need to do something to notice that it had crashed and then raise an exception, but definitely possible

**Comment by bmoscon** [comment]
old version is deprecated, closing
