### ISSUE TITLE
expect an example.py for reconstructing the orderbook

### ISSUE THREAD

**Issue by xiandong79** [bmoscon/cryptostore#21]
For example, I use the following config.yaml with command cryptostore.

```
book_depth: null
book_delta: True
book_delta_window: 20000
```

Is there any example.py or READMD.md to illustrate that how to reconstruct the orderbook from the stored data (when I use `book_delta` to store the update).

**Comment by xiandong79** [comment]
After I get the book, there are both 'delta' = True and False in the book. What the meaning of 'delta', how can I reconstruct the order book using 'delta'?

Any documentation or example? @bmoscon

**Comment by bmoscon** [comment]
delta is an indicator if the data is an update or part of a complete orderbook. The complete order book is found where the deltas are false for a single timestamp. Use those to build the initial book. Then apply the deltas (where delta is true) to obtain the book for each interval. Snapshots are periodically stored (this is configurable) so you'll eventually see updates where delta is False again.

**Comment by bmoscon** [comment]
example is here:
https://github.com/bmoscon/cryptostore/blob/master/examples/book_build.py

will build a book update by update from arctic.
