### ISSUE TITLE
log-config.json no such file or directory

### ISSUE THREAD

**Issue by weiminmei** [bmoscon/cryptostore#218]
Hello!

When trying to start up the container using the instructions:

`docker run -e EXCHANGE='COINBASE' -e CHANNELS='l2_book' -e SYMBOLS='BTC-USD' -e BACKEND='MONGO' -e DATABASE='cryptofeed' ghcr.io/bmoscon/cryptostore:latest -d`

I notice the container did not start. Checking the logs showed this error:

`log-config.json: no such file or directory`

**Comment by bmoscon** [comment]
cant reproduce
