### ISSUE TITLE
Config.yaml example no longer in repository

### ISSUE THREAD

**Issue by sdk451** [bmoscon/cryptostore#223]
**Describe the bug**
The documentation refers to a config.yaml file in the root of this repository.  This doesn't appear to be there anymore.

**To Reproduce**
Try running the latest docker container. It fails when it looks for the local config.yaml. I'd love to supply one but without a template I have no idea what should be in it...

**Expected behavior**
An example config.yaml file?

**Comment by c0indev3l** [comment]
It seems to be there
https://github.com/bmoscon/cryptostore/blob/master/tools/config.yaml
