### ISSUE TITLE
Several candles time interval

### ISSUE THREAD

**Issue by c0indev3l** [bmoscon/cryptostore#231]
Hello,

I wonder if cryptostore can be used to store several candles timeframe for several symbols

I noticed `CANDLE_INTERVAL` environment variable but looking at code

https://github.com/bmoscon/cryptostore/blob/78a9f157799b7b789ccbc8ab835200e69ce8d919/cryptostore.py#L151

it seems that only one candle_interval is passed.

What workaround do you suggest?

Kind regards

**Comment by bmoscon** [comment]
cryptofeed only supports one candle interval per feed. if you need multiple, you have to set up multiple feeds
