### ISSUE TITLE
Coinbase - code 1006 <connection closed abnormally>

### ISSUE THREAD

**Issue by xiandong79** [bmoscon/cryptostore#28]
After a while (several hours), the **coinbase websockets** disconnects and gives ConnectionClosed: Websockets connection is closed: code = 1006 <connection closed abnormally [internal]>

It seems that this case has been discussed in the following issues:
https://github.com/aaugustin/websockets/issues/367
https://github.com/aaugustin/websockets/issues/579

I know that cryptostore would reconnect the WebSocket. **So, this error message should not bother too much.** 

Also I noticed that https://websockets.readthedocs.io/en/stable/contributing.html#bitcoin-users
"""
Bitcoin users
websockets appears to be quite popular for interfacing with Bitcoin or other cryptocurrency trackers. I’m strongly opposed to Bitcoin’s carbon footprint.

Please stop heating the planet where my children are supposed to live, thanks.

Since websockets is released under an open-source license, you can use it for any purpose you like. However, I won’t spend any of my time to help.

I will summarily close issues related to Bitcoin or cryptocurrency in any way.
"""

**Comment by bmoscon** [comment]
Not sure if this is a question, or something else. I use coinbase, and I've had a connection to them for weeks at a time without seeing this issue, but sometimes it does happen. I dont think there is much that can be done here other than to reconnect. If you turn on websocket's debug facility you'll get much more information (but be forewarned, its a LOT of information).

**Comment by xiandong79** [comment]
Also, I use l3_book for coinbase currently. I will change to subscribe the l2_book.

I agree with you that "there is much that can be done here other than to reconnect. "

**Comment by jpic** [comment]
So, do you think reconnection can be done at this lib's level ? ie. try to reconnect, and raise an error only if reconnecting failed N times ?
