### ISSUE TITLE
bitfinex (all exchanges) - should never stop retry the connection. 

### ISSUE THREAD

**Issue by xiandong79** [bmoscon/cryptostore#30]
in 2019-08-01，bitfinex.com is down for an upgrade.

all API said: 
```
{
code: 503,
error: "temporarily_unavailable",
error_description: "Sorry, the service is temporarily unavailable. See https://www.bitfinex.com/ for more info."
}
```
In bitfinex.com:
“Please monitor bitfinex.statuspage.io and twitter.com/bitfinex for updates.”

However, after bitfinex.com restarted to offer the market data, Cryptostpre or Cryptofeed did not start to colllect the market data.

**Comment by xiandong79** [comment]
or with `code: 503`,  the Cryptostpre or Cryptofeed should not stop retry.

**Comment by bmoscon** [comment]
I'll but some code in to the config to let the end user set their timeout options

**Comment by bmoscon** [comment]
fixed on master - users can now specify number of times to retry a connection
