### ISSUE TITLE
Arctic quota exceeded

### ISSUE THREAD

**Issue by nateGeorge** [bmoscon/cryptostore#31]
After collecting L2 data for a few days, I hit a snag with the Arctic quota being exceeded.  I'm not sure of the best way to deal with this.  Any tips or ideas?

```python
ERROR:asyncio:Task exception was never retrieved
future: <Task finished coro=<Aggregator.loop() done, defined at /home/nate/anaconda3/lib/python3.6/site-packages/cryptostore/aggregator/aggregator.py:38> exception=QuotaExceededException('Mongo Quota Exceeded: arctic.HITBTC 11.653 / 10 GB used',)>
Traceback (most recent call last):
  File "/home/nate/anaconda3/lib/python3.6/site-packages/cryptostore/aggregator/aggregator.py", line 64, in loop
    store.write(exchange, dtype, pair, time.time())
  File "/home/nate/anaconda3/lib/python3.6/site-packages/cryptostore/data/storage.py", line 36, in write
    s.write(exchange, data_type, pair, timestamp)
  File "/home/nate/anaconda3/lib/python3.6/site-packages/cryptostore/data/arctic.py", line 43, in write
    self.con[exchange].append(f"{data_type}-{pair}", df, upsert=True, chunk_size=chunk_size)
  File "/home/nate/anaconda3/lib/python3.6/site-packages/arctic/chunkstore/chunkstore.py", line 523, in append
    self.__update(sym, item, metadata=metadata, combine_method=SER_MAP[sym[SERIALIZER]].combine, audit=audit)
  File "/home/nate/anaconda3/lib/python3.6/site-packages/arctic/chunkstore/chunkstore.py", line 417, in __update
    self._arctic_lib.check_quota()
  File "/home/nate/anaconda3/lib/python3.6/site-packages/arctic/arctic.py", line 609, in check_quota
    to_gigabytes(self.quota)))
arctic.exceptions.QuotaExceededException: Mongo Quota Exceeded: arctic.HITBTC 11.653 / 10 GB used
```

**Comment by nateGeorge** [comment]
It also seems this may be related to another issue I noticed, which is the redis memory would max out and crash/cause errors.  I think it's due to the HitBTC trades (BTC-USD).

**Comment by bmoscon** [comment]
You have to set the quota manually, it defaults to 10 GB. You can do so like so:


import arctic
a = arctic.Arctic('127.0.0.1')
a.set_quota('library_name', size_in_bytes)

**Comment by bmoscon** [comment]
you need to make sure you have the space for redis, it will store data in memory until its consumed into a storage engine, at which point it should delete the data from redis. make sure the trade interval is set to a reasonable range for your use case

**Comment by xiandong79** [comment]
it runs well with 98 pairs in 6 exchanges with redis, influxdb, parquet for more than 2 weeks. 
Great work!

**Comment by xiandong79** [comment]
@nateGeorge what about your `storage interval`? 

 `storage interval` is related to how many data would be stored by Redis (in memeory) until the data be removed to influxdb, parquet or atctic.

**Comment by nateGeorge** [comment]
The comment in config.yaml says "# Data batching window, in seconds".  I had it at the value of 60 in the example, then changed it to 30.  The runaway memory issue seems to be due to some other problems, like when the arctic quota is exceeded and/or other problems with a few exchanges.  If the data is not written, it piles up in Redis and crashes, or errors out until cryptostore is re-run (and clears the cache).

**Comment by nateGeorge** [comment]
But for now it seems to be working after I changed the arctic quota for coinbase and hitbtc to a higher value.
