### ISSUE TITLE
enable redis config for unix domain sockets

### ISSUE THREAD

**Issue by bohuspollak** [bmoscon/cryptostore#32]
enable redis config for Sockets

**Comment by bmoscon** [comment]
I assume you mean the unix domain socket?

**Comment by bohuspollak** [comment]
Yes. Currently Cryptofeed/Cryptostore do not enable unix sockets in config.
I have been looking at the code, trying to add the feature but might be more complex as it touches also the cryptofeed. Looks like the aggregator is creating connection pools only for redis type of connection.
The schema redis:// is hardcoded
https://github.com/bmoscon/cryptofeed/blob/master/cryptofeed/backends/redis.py#L50

the config do not allow this option, only IP and PORT
https://github.com/bmoscon/cryptostore/blob/master/cryptostore/aggregator/aggregator.py#L40

The connection pool is created for redis only.

If you let me know how you want to make it I can try to add this feature.

Should be done pretty easy on connection using the connection_class=UnixDomainSocketConnection

**Comment by bmoscon** [comment]
I added support for it on the cryptofeed end, just need to add support for it on the store side. Hopefully in the coming week can resolve/close this out

**Comment by bmoscon** [comment]
fixed on master
