### ISSUE TITLE
aggregator thread died without any notificatin. 

### ISSUE THREAD

**Issue by xiandong79** [bmoscon/cryptostore#33]
Background:
1. Today is a great market day with tons of orders and trades in all exchanges.
2. As you know, the storage_interval for me is 1800 seconds for parquet and 1800 seconds for influxdb.

Case:
when the aggregator thread wants to write the data of Coinbase l3_book_BTC-USDT from Redis to influx or parquet. (I know, using l3_book is not a good idea as I only have 8GB memory. I have changes to subscribe the l2_book for Coinbase)

the data bursts/overwhelms the memory and the aggregator thread is dead. 

However, when the process failed to write, the program itself just hangs on (`tail -f nohup.out` also hangs on) while the aggregator thread is dead already.

I think some log info or raise an exception is expected?

**Comment by bmoscon** [comment]
yes, I'll look into making sure an error is logged if the aggregator dies

**Comment by bmoscon** [comment]
fixed on master
