### ISSUE TITLE
okcoin change into okex！

### ISSUE THREAD

**Issue by otccoin** [bmoscon/cryptostore#37]
okcoin change into okex！

**Comment by bmoscon** [comment]
Not sure what this means.

**Comment by otccoin** [comment]
www.okex.com

**Comment by bmoscon** [comment]
yeah, cryptofeed supports both. okex and okcoin.

**Comment by bmoscon** [comment]
there isnt enough information for me to discern what the issue is - so closing. feel free to re-open when/if you can supply more information
