### ISSUE TITLE
HUOBI_DM - the keys in redis do not match the keys in cryptostore

### ISSUE THREAD

**Issue by xiandong79** [bmoscon/cryptostore#41]
@glgnohk @bmoscon  error in the cryptostore!!!

in redis: 
```
127.0.0.1:6379> KEYS '*'
 1) "l2_book-HUOBI_DM-ETH190927"
 2) "trades-HUOBI_DM-ETH190830"
 3) "trades-HUOBI_DM-BTC190830"
 4) "trades-HUOBI_DM-BTC190927"
 5) "trades-HUOBI_DM-ETH190906"
 6) "l2_book-HUOBI_DM-ETH190830"
 7) "l2_book-HUOBI_DM-ETH190906"
 8) "l2_book-HUOBI_DM-BTC190830"
 9) "trades-HUOBI_DM-BTC190906"
10) "l2_book-HUOBI_DM-BTC190906"
11) "trades-HUOBI_DM-ETH190927"
12) "l2_book-HUOBI_DM-BTC190927"
```

However, in cryptostore, cryptostore wants to save the 
```
019-08-26 15:14:38,914 : INFO : No data for HUOBI_DM-l2_book-ETH_NW
2019-08-26 15:14:38,914 : INFO : Reading HUOBI_DM-l2_book-ETH_CQ
2019-08-26 15:14:38,915 : INFO : No data for HUOBI_DM-l2_book-ETH_CQ
2019-08-26 15:14:38,915 : INFO : Reading HUOBI_DM-trades-BTC_CW
2019-08-26 15:14:38,915 : INFO : No data for HUOBI_DM-trades-BTC_CW
2019-08-26 15:14:38,915 : INFO : Reading HUOBI_DM-trades-BTC_NW
2019-08-26 15:14:38,915 : INFO : No data for HUOBI_DM-trades-BTC_NW
2019-08-26 15:14:38,915 : INFO : Reading HUOBI_DM-trades-BTC_CQ
2019-08-26 15:14:38,915 : INFO : No data for HUOBI_DM-trades-BTC_CQ
2019-08-26 15:14:38,916 : INFO : Reading HUOBI_DM-trades-ETH_CW
2019-08-26 15:14:38,916 : INFO : No data for HUOBI_DM-trades-ETH_CW
2019-08-26 15:14:38,916 : INFO : Reading HUOBI_DM-trades-ETH_NW
2019-08-26 15:14:38,916 : INFO : No data for HUOBI_DM-trades-ETH_NW
```

**Comment by glgnohk** [comment]
I don't know how the cryptofeed backends or cryptostore work. But Huobi does have a different subscription model than other exchanges. See:

https://github.com/bmoscon/cryptofeed/blob/89ede4800e00f6fcba03e9e3e26e8fe7181a23c6/cryptofeed/exchange/huobi_dm.py#L2

and

https://github.com/bmoscon/cryptofeed/blob/89ede4800e00f6fcba03e9e3e26e8fe7181a23c6/cryptofeed/pairs.py#L158

Maybe just need a exact definition of how the exchange pair name mappings are used (https://github.com/bmoscon/cryptofeed/blob/89ede4800e00f6fcba03e9e3e26e8fe7181a23c6/cryptofeed/standards.py#L26)

**Comment by xiandong79** [comment]
The data in Redis with key `l2_book-HUOBI_DM-ETH190927` can not be extracted by key `HUOBI_DM-l2_book-ETH_NW`. 

So, is the current mapping standard `{'ETH_NW' ：'ETH190927' }` a good idea? Or we should just save 
the string of pair with `ETH_NW`?

**Comment by glgnohk** [comment]
> So, is the current mapping standard {'ETH_NW' ：'ETH190927' } a good idea? Or we should just save
> the string of pair with ETH_NW in cryptofeed and cryptostore ?
> @bmoscon 

I thought about this when doing HUOBI_DM. If you publish like ETH_CW, then you are going to have to convert it's expiry when you back test. E.g. You use ETH_NW, and today it's expiry is 20190823 for example, then tomorrow it's expiry is 20190830, a completely different instrument.

**Comment by glgnohk** [comment]
We could possibly change the mapping to {'ETH190927': 'ETH_NW'} in cryptofeed, if that helps with   cryptostore. Anyway, I think that Huobi_DM introduces a model not really planned for initially.

**Comment by xiandong79** [comment]
> We could possibly change the mapping to {'ETH190927': 'ETH_NW'} in cryptofeed, if that helps with cryptostore. Anyway, I think that Huobi_DM introduces a model not really planned for initially.

Because the `expire day` may change every day. Using currently method, we may have to relaunch the Cryptostore/Cryptofeed program everyday to get the everyday/active pair mapping.

**Comment by xiandong79** [comment]
Maybe use `ETH_NW`, `ETH_CW` directly is easier for the case of HUOBI_DM, and the different instrument with different expire_day can be distinguished by their timestamp in the data.

**Comment by glgnohk** [comment]
All the other exchanges subscribe and publish using format like ETH190927. For these, you're anyway going to have to resubscribe when the new expiries are listed.

Have you stored data across a Huobi_DM expiry change. I may have and will have to check. I wonder if it just picks up the new expiries automatically? Even if it does, yeah it won't be in the `_std_trading_pairs1` and `_exchange_to_std` dicts.

**Comment by bmoscon** [comment]
i'd say these should be done just like the bitmex ones are - you have to look up the symbols explicitly and subscribe to them. XBTUSD is a special case because it never expires, but the other expiring contracts have no mappings, there is a help method to look them up and subscribe. I'd think using the "helper" symbols is fine, but for cryptostore you'll need to use the actual symbol id, i.e. `ETH190927`

**Comment by xiandong79** [comment]
is it good to add a judgment in `cryptostore/aggregator/aggregator.py`, and tanslate the ETH_CQ to ETH190927.

```python
for pair in self.config.exchanges[exchange][dtype] if 'symbols' not in self.config.exchanges[exchange][dtype] else self.config.exchanges[exchange][dtype]['symbols']:
    if exchange == 'HUOBI_DM':
        pair = cryptofeed.cryptofeed.pairs.huobi_dm_pairs()[pair]
```

**Comment by bmoscon** [comment]
@xiandong79 so you'd use the _CQ symbol in the config but it would be stored under the proper mapping, i.e. ETH190972 ?

**Comment by glgnohk** [comment]
Note that `Bitmex.get_active_symbols()` outputs all traded instruments: futures, swaps, and options (warrants):
```
['XRPU19',
 'BCHU19',
 'ADAU19',
 'EOSU19',
 'TRXU19',
 'XBTUSD',
 'XBT7D_U105',
 'XBT7D_D95',
 'XBTU19',
 'XBTZ19',
 'ETHUSD',
 'ETHU19',
 'LTCU19']
```

But `OKEx.get_active_symbols()` outputs only futures (there's a separate channel for futures and swaps):
```
['BTC-USD-190913',
 'BTC-USD-190920',
 'BTC-USD-190927',
 'LTC-USD-190913',
 'LTC-USD-190920',
 'LTC-USD-190927',
...]
```

The function is called  `get_active_symbols()`, so should probably return everything, but we could add `get_active_futures()`. Anyway, just bringing up so we're consistent and agree on what this function should do.

**Comment by xiandong79** [comment]
> @xiandong79 so you'd use the _CQ symbol in the config but it would be stored under the proper mapping, i.e. ETH190972?


yes. in Redis, we have a key like "l2_book-HUOBI_DM-ETH190906", but current Cryptostore would try to get the data by key "l2_book-HUOBI_DM-ETH_CW".

all the HUOBI_DM data would be left in the redis and memory crash finally.

**Comment by xiandong79** [comment]
still could not be solved.

the cryptofeed and cryptostore have to be launched every day.
