### ISSUE TITLE
[feature request] exchange-send-time VS arrived-time for orderbook

### ISSUE THREAD

**Issue by xiandong79** [bmoscon/cryptostore#44]
From binance.py, we know the `event_time` is recorded in the files/storage.
from biemex.py, we know the `arrived_time` is recorded in the files/storage. Also, we know bitmex exchange does not provide a book_update timestamp for users.

What is the design philosophy of 'timestamp' field in the cryptostore? 

why not record 2 timestamps? one is exchange_time, one is arrive_time? 
Do you guys need this feature?

**Comment by zhenpingfeng** [comment]
In my code fork, I just add a recv_timestamp field for myself. I think arrive_time is important for some latency sensitivity trading strategies.
https://github.com/zhenpingfeng/cryptofeed/blob/2f5f192e19a9a1c885ce72d48dd3bcff57758327/cryptofeed/backends/rabbitmq.py#L61-L62

**Comment by bmoscon** [comment]
the timestamp in cryptostore comes from cryptofeed, so I'm not sure what you're asking. Cryptostore should not be adding timestamps to data.

**Comment by xiandong79** [comment]
> the timestamp in cryptostore comes from cryptofeed, so I'm not sure what you're asking. Cryptostore should not be adding timestamps to data.

what about adding a arrived_time or received_time in the cryptofeed?

**Comment by bmoscon** [comment]
@xiandong79 so you want more timestamps, right? I can add optional support for requesting cryptostore received timestamp and cryptofeed received timestamp, but I personally think that the cryptostore received timestamp is not useful, the data is aggregated, so its not realtime. I could add the timestamp from the backend (i.e. redis or kafka) so you could see the exchange timestamp, the cryptofeed timestamp and the timestamp the aggregator assigned to it when written. what do you think?

**Comment by xiandong79** [comment]
Thanks, really appreciate your illustration.
I think I should customize it myself.

**Comment by hh2010** [comment]
@xiandong79 were you able to find a solution this?

I am also interested in the exchange timestamp which is currently not available in cryptostore

**Comment by bmoscon** [comment]
@hh2010 the timestamp is the timestamp from the exchange
