### ISSUE TITLE
[Parquet][bitmex] timestamp nanoseconds precision lost

### ISSUE THREAD

**Issue by tarahirion** [bmoscon/cryptostore#45]
Hi all,
when reading back and converting to pandas the parquet file, I noticed the timestamp nanoseconds precision is lost thus rendering the orderbook reconstruction quit difficult.
Do you have any workaround?
Best

**Comment by tarahirion** [comment]
Sorry if I missed the point but is every orderbook update stored in a new parquet file?
If yes does each parquet contain the full orderbook and not only the level specified in the config.yaml?

**Comment by bmoscon** [comment]
I saw you closed this, wasn't sure if you had your questions answered @tarahirion . 

Every parquet file is NOT  a full orderbook - its all the data within the time interval specified in the config. If your collection interval is 6 hours, each file is 6 hours of data. Assuming you are collecting deltas, you need to find a snapshot and add deltas to that. The snapshot entries will all have the same timestamp. Does this answer your question?

**Comment by tarahirion** [comment]
Sure, many thanks!
One more little question,
Initially I was able to fetch the x-level orderbook at every update without delta (while using artic) but if I try it now with parquet and I receive an error : WebSocket closed with code 1006.
Is it a normal behavior or something went wrong?
