### ISSUE TITLE
Error running "cryptostore" command from bash 

### ISSUE THREAD

**Issue by smatiush** [bmoscon/cryptostore#49]
hi,
i installed cryptostore from pip using the command `pip3 install cryptostore`
the installation went fine but when i execute the command `cryptostore` from the bash to run the storage python gives me back this:

`Traceback (most recent call last):
  File "/home/cg/.local/bin/cryptostore", line 11, in <module>
    sys.exit(main())
  File "/home/cg/.local/lib/python3.6/site-packages/cryptostore/bin/cryptostore.py", line 11, in main
    cs = Cryptostore(config=args.config)
  File "/home/cg/.local/lib/python3.6/site-packages/cryptostore/cryptostore.py", line 30, in __init__
    self.plugin.start()
  File "/home/cg/.local/lib/python3.6/site-packages/cryptostore/plugin/controller.py", line 29, in start
    if 'plugins' in self.cfg:
TypeError: argument of type 'NoneType' is not iterable
`
how can this problem be solved?

**Comment by bmoscon** [comment]
this seems to mean you have no config file, or at least are not specifying one or running from the correct directory.

**Comment by smatiush** [comment]
thanks a lot for the answer! now cryptostore is returning `kafka.errors.ConnectionError: ConnectionError: Unable to bootstrap from [('127.0.0.1', 2181, <AddressFamily.AF_INET: 2>)]`
do i need to set up some type of config in kafka?

**Comment by bmoscon** [comment]
if you want to use kafka, yes. You'll need to have either a working kafka setup or a working redis setup. You'll need to supply the info for those instances/clusters in the config.yaml

**Comment by smatiush** [comment]
i do have it set up, i did try to config the yaml file by changing the port; is there anything else i should fiddle with? 

(attached is my config file)
![Schermata da 2020-01-18 14-47-07](https://user-images.githubusercontent.com/24374501/72664731-84772300-3a01-11ea-9eb3-243aa26126d4.png)

**Comment by bmoscon** [comment]
the error above indicates that something is wrong with your kafka setup. Kafka is harder to configure and use than redis (in my opinion), so if you're not comfortable debugging kafka you may want to use redis.

**Comment by smatiush** [comment]
thanks for every answer! very helpful.
the problem was solved installing redis
