### ISSUE TITLE
instrument and open_interest

### ISSUE THREAD

**Issue by bonald** [bmoscon/cryptostore#50]
Hi,

Is it possible to have instrument and open_interest from cryptofeed too ?

**Comment by bmoscon** [comment]
yes - will work on this soon

**Comment by bmoscon** [comment]
open interest data now supported! The instrument type was removed and was consistently renamed open interest for all exchanges.

**Comment by bonald** [comment]
updated cryptostore/cryptofeed and changed my config to:

exchanges:
    BITMEX:
        retries: -1
        trades: [XBTUSD, XBTH20, XBTM20, ETHUSD, ETHH20, ADAH20, BCHH20, LTCH20, TRXH20, XRPH20]
        funding: [XBTUSD, ETHUSD]
        open_interest: [XBTUSD, ETHUSD]

but I get no data:
No data for BITMEX-open_interest-XBTUSD

**Comment by bonald** [comment]
@bmoscon

**Comment by bmoscon** [comment]
@bonald the data is not by symbol, its by exchange/data type, so the data is in "open_interest-BITMEX";


so:

select * from "open_interest-BITMEX";
