### ISSUE TITLE
InfluxDB can't query when using cryptostore 

### ISSUE THREAD

**Issue by smatiush** [bmoscon/cryptostore#52]
I've saved all the Bitmex tick data to an influxDB database using cryptostore. The default name cryptostore gave to the DB is "trades-BITMEX". The problem is that influxDB doesn't accept the character "-" in it's queries, and gives me error 400. Is there a workaround for this? Or can I change the default name that cryptostore gives to databases to a custom one and then repopulate?

**Comment by Konembed** [comment]
You can specify the db name explicitly in the config.yaml to avoid including a hypen in the name., e.g.:


influx:
    host: '<INFLUX_HOST>:<PORT>'
    db: DBNAME
    create: true

**Comment by bmoscon** [comment]
@smatiush can give you me an example where it wont work? The DB name is no trades-bitmex, thats the table or collection (or however you choose to think about it). I can query from it just fine. 

```
➜ influx
Connected to http://localhost:8086 version v1.7.9
InfluxDB shell version: v1.7.9
> use example;
Using database example
> select * from "l2_book-BITMEX";
name: l2_book-BITMEX
time                amount  delta pair   price  side timestamp
----                ------  ----- ----   -----  ---- ---------
1578615270682065963 2700559 False XBTUSD 7832   bid  1578615270.682066
1578615270682065964 204016  False XBTUSD 7831.5 bid  1578615270.682066
1578615270682065965 137094  False XBTUSD 7831   bid  1578615270.682066
1578615270682065966 219395  False XBTUSD 7830.5 bid  1578615270.682066
1578615270682065967 511272  False XBTUSD 7830   bid  1578615270.682066
1578615270682065968 205321  False XBTUSD 7829.5 bid  1578615270.682066
1578615270682065969 74803   False XBTUSD 7829   bid  1578615270.682066
```

**Comment by bmoscon** [comment]
@smatiush please provide more information regarding this or I'll assume its working for you (since it works for me) and I'll close this.

**Comment by bmoscon** [comment]
going to close this. Please re-open if this issue persists (but please supply more information before doing so).
