### ISSUE TITLE
cryptostore dies if influxdb doesn't respond

### ISSUE THREAD

**Issue by bonald** [bmoscon/cryptostore#53]
Hello!

When influxdb goes down for a minute or two, cryptostore doesn't restart it just dies.
It should retry to connect to influx every x. I have to manually restart the process and it looks like redis is not keeping data in cache because there's a gap in the timestamps.

**Comment by bmoscon** [comment]
I can change it to retry on the next interval if it can't connect and not clear the data until it successfully writes it to influx. The data may be getting removed when you restart, unless you have the flush cache setting to false

**Comment by bonald** [comment]
OOk great

**Comment by bmoscon** [comment]
fixed!
