### ISSUE TITLE
Suggestions for book_interval (time interval instead of count)

### ISSUE THREAD

**Issue by joelrich** [bmoscon/cryptostore#56]
With parquet files, I think it makes a lot of sense to only store a single snapshot per file (at the very beginning) since this allows to read files individually.

Alternatively, I would prefer if I could configure book_interval with a time interval, e.g. 24h. This would also make it easier to know how much of the history has to be read to surly have a snapshot while keeping the stored volume small.

What do you think?

**Comment by bmoscon** [comment]
@joelrich I like that idea, its a bit of work, but I do like it. I'll try and get it done later next week or the week after, or happy to take a PR :D

**Comment by bmoscon** [comment]
This is two issues really. I'm going to close this and open another one with the part about snapshots only being at the start of the storage interval.
