### ISSUE TITLE
Binance futures: snaphot has no overlap with first update

### ISSUE THREAD

**Issue by joelrich** [bmoscon/cryptostore#57]
I get the "snaphot has no overlap with first update" error pretty often when Binance futures connects. From implementing my own Binance futures integration, I know that the issue can be solved by simply waiting for 2 events before fetching the snapshot.

**Comment by bmoscon** [comment]
I think this has been fixed - can you confirm? You'll need to use the version in github (of cryptofeed). I just pushed an update a few minutes ago

**Comment by joelrich** [comment]
Sorry, I haven't had time to test this yet. But I will eventually update the thread (may take another week).

**Comment by joelrich** [comment]
Can confirm. Hasn't happened anymore.
