### ISSUE TITLE
Database bottleneck?

### ISSUE THREAD

**Issue by rbdm-qnt** [bmoscon/cryptostore#59]
I'm using InfluxDB and getting trade and l2 order book data for XBTUSD, Bitmex.

I tried to get 100 slots of the Order Book instead of the standard 25 (with the delta off), and cryptostore started giving me those warnings:

WARNING : Storage operations currently take 0.4 seconds, longer than the interval of 0

If I try to get more, like 200 slots, it eventually gets to 1 minute and more. Is this an influxDB bottleneck? I imagine if I took trade and OB data for multiple pairs, even with just 25 slots, it would be too much. 

I'm also asking around in the InfluxDB forums, as I understand it's none of your fault if their software can't keep up; just checking if it's just me or a known issue.

**Comment by bmoscon** [comment]
why is the interval set to 0? Thats going to generate a lot of load, it should be set to something like 30, 60, 120, etc.

**Comment by rbdm-qnt** [comment]
The book interval is not present in the Bitmex part of the config. I tried adding it after book_delta but I got the same exact warning as before, "...longer than the interval of 0". 
The good news is if I turn the book_delta on it can take 10 times the depth without any issue!

exchanges:
    BITMEX:
        retries: -1
        l2_book:
            symbols: [XBTUSD]
            max_depth: 200
            book_delta: False
        trades: [XBTUSD]
#        ticker: [XBTUSD]
#        funding: [XBTUSD]
#    COINBASE:
#        retries: -1
#        l3_book:
#            symbols: [BTC-USD, ETH-USD]
#            book_delta: true
#            book_interval: 10000
#        trades: [BTC-USD, ETH-USD, ETH-BTC]
#        ticker: [BTC-USD]

**Comment by bmoscon** [comment]
Not book interval, storage interval:

https://github.com/bmoscon/cryptostore/blob/master/config.yaml#L108

**Comment by rbdm-qnt** [comment]
Set the interval to 30 and it improved slightly. If I keep the delta off it keeps lagging anyway. Gonna use delta, no problem; one last question, if I get a new snapshot every time the OB changes, what does the book interval refer to? Is it the update interval in case there is no new orders in the OB?

**Comment by bmoscon** [comment]
if you dont use the delta, you're getting full books every time, so with max depth of 200, thats 400 rows to the DB every time there is an update (so multiple times a second). You could be writing 5k+ updates per symbol for that one exchange. Thats a lot of data. Its doable but you'll probably need a dedicated database cluster. With deltas you're just writing the changes each time there is an update, so far less data. The book interval is used to periodically write full books, every book_interval updates. This is so you can build a full book without having to read ALL the data. you find a snapshot and then apply updates to it from that point on, until you reach another snapshot, etc.

**Comment by rbdm-qnt** [comment]
Got it! Thank you for your hard work :-)

**Comment by bmoscon** [comment]
going to close this since it seems like you're all set. let me know if you have more questions.
