### ISSUE TITLE
Snapshot control

### ISSUE THREAD

**Issue by bmoscon** [bmoscon/cryptostore#60]
see issue #56 

Request is that parquet files have the snapshot at the beginning, and then just deltas afterwards. So if files are written every 4 hours, each file would have the snapshot to start with, and then all deltas. 

Easy to do, but how do you handle a disconnect? You'd get a snapshot again, even in the middle of a time window. Also, a snapshot and a delta are no different in terms of how you handle them, so having a snapshot in the middle of the file should be irrelevant. The only to do here really should be to make sure the first data in a time window for books is the snapshot

@joelrich - does this do justice to your request in #56  ?

**Comment by joelrich** [comment]
Yes, this would be great. Is there already a way to get the full order book by calling a a method on an exchange (after the initial connect)?

**Comment by yohplala** [comment]
Hi @bmoscon,

Given my current trouble with Redis, and your answer that I may retrieve too much data, it seems that the next step for me to relieve my server from some workload is this feature.
(at the moment, book delta has its default value: 1000 - I am wondering if I could no reduce 'significantly' the workload by having the full snapshot at the beginning of the parquet file)

You indicate 'easy to do'.

Do you have some plan to do this?

I could start to have a look maybe?
thanks for the pointers you can share, if any.
Have a good day,
Bests,

**Comment by bmoscon** [comment]
Its on my radar, but not something I'm doing soon. You can bump that value from 1000 to something higher like 100k or even 1 million.
