### ISSUE TITLE
Feature: Add exchange TAG to influx.py

### ISSUE THREAD

**Issue by bonald** [bmoscon/cryptostore#63]
We can't really aggregate data into another database without having an exchange tag.
In influxdb, you can't "group by" using measurement name. 
So right now we can only use the pair tag, the problem is that exchanges all share the same pair name.

Easy fix:
{data_type}-{exchange},pair={pair},exchange={exchange}

**Comment by bmoscon** [comment]
@bonald seems reasonable, I can add this

**Comment by bmoscon** [comment]
merged
