### ISSUE TITLE
soket.recv() stuck in infinite error 

### ISSUE THREAD

**Issue by smatiush** [bmoscon/cryptostore#64]
hi,
i'm trying a connection via zmq in python, 
this is my code:
`import zmq
import json
import time
def socket_trades():
    ctx = zmq.Context.instance()
    socket = ctx.socket(zmq.SUB)
    socket.setsockopt(zmq.SUBSCRIBE, b"BITMEX-trades-XBTUSD")
    socket.connect('tcp://127.0.0.1:5678')
    while True:
        try:
            msg = socket.recv_string(zmq.NOBLOCK)
            yield json.loads(msg[21:])
            #yield json.loads(msg_book)
        except zmq.error.Again:
            print("zmq.NOBLOCK")
            time.sleep(1)
        continue

while True:
    for a in socket_trades():
        print(a)
        time.sleep(1)`

the problem is here "msg = socket.recv_string(zmq.NOBLOCK)".
in this snippet i use "socket.connect('tcp://127.0.0.1:5678')", if i change it in socket.bind('tcp://127.0.0.1:5678') everythings works fine,
i can't use bind because it's impossible to handle more than 1 topics.
how can i solve this?

**Comment by bmoscon** [comment]
whats the infinite error? If you use noblock its going to raise an error until a message is available.

**Comment by smatiush** [comment]
![Schermata da 2020-03-02 10-18-07](https://user-images.githubusercontent.com/24374501/75662338-334c8700-5c6f-11ea-8107-fedb1e5680f5.png)
i left the code running for a while, but the function block the exgution of the program, like the "Keyboard Interrupt" return

**Comment by smatiush** [comment]
![Schermata da 2020-03-02 10-35-20](https://user-images.githubusercontent.com/24374501/75663725-9808e100-5c71-11ea-93db-2083684e597a.png)
i left the code running for a while(more or less 30min), but the function socket.recv() remains stuck and blocks the execution of the program

**Comment by cheekybastard** [comment]
@smatiush cryptostore/cryptofeed requires python  >= 3.7. The file path in your error msg shows python 3.6 in venv.

**Comment by smatiush** [comment]
thx @cheekybastard but it didn't solve the problem

**Comment by bmoscon** [comment]
@smatiush i'll need your cryptostore config to see if i can reproduce it

**Comment by xiandong79** [comment]
I face the same issue I think.

**Comment by bmoscon** [comment]
i published sample code in `examples/zmq_pass_through.py`
