### ISSUE TITLE
Memory usage possible issue

### ISSUE THREAD

**Issue by rbdm-qnt** [bmoscon/cryptostore#66]
Hi! I'm using a Mac with 10.12.6 OS. When I run redis, influx and cryptostore to get data, I notice my RAM is always 100% full at all times, and if I try to clear it with one of those memory cleaning apps it gets filled up again in less than 5 seconds. Today I just let it run to max all day, and by the end of the day my SSD (that's my only drive, I'm on a macbook) was full, and my terminal froze. I thought that maybe Influx had used all the 40GBs I had left, but when I restarted the computer all was fine, I had 39GBs free, and Influx had only stored 1GB of data (which was correct). 

Anybody ever had a similar problem? Could it be possible that either redis, influx or cryptostore has RAM usage issues, and that it gets momentarily stored on hard drive as cache or something?
Would love to know if anybody had this issue on Linux, since I'm gonna run this on a VPS.

**Comment by bmoscon** [comment]
redis uses a lot of memory and it will store to disk periodically. I disable that option so its 100% in memory

**Comment by rbdm-qnt** [comment]
Thanks for the quick reply; where did you edit those settings? Redis config or via terminal?

**Comment by bmoscon** [comment]
on mac if you installed with homebrew its in /usr/local/etc/redis.conf

**Comment by rbdm-qnt** [comment]
Thank you very much! Keep up the great work, loving cryptostore so far and your support is great :-)

**Comment by bmoscon** [comment]
going to close this since I believe there is nothing to do. please reopen if you feel something still needs to be addressed
