### ISSUE TITLE
Character based intervals do not cause aggregation on clock times

### ISSUE THREAD

**Issue by chazzmoney** [bmoscon/cryptostore#70]
The test that ensures if an interval is 'M' that it happens on the clock minute is found [here](https://github.com/bmoscon/cryptostore/blob/master/cryptostore/util.py#L13).

This function is called by the aggregator [here](https://github.com/bmoscon/cryptostore/blob/master/cryptostore/aggregator/aggregator.py#L79).

However, when the variable ‘interval’ is passed into get_time_interval, it has already been coerced into an integer value [here](https://github.com/bmoscon/cryptostore/blob/master/cryptostore/aggregator/aggregator.py#L65).

I believe that this is a bug and prevents any of the [non-integer interval logic in the util function](https://github.com/bmoscon/cryptostore/blob/master/cryptostore/util.py#L13-L21) from being executed.

**Comment by bmoscon** [comment]
Can you explain what the issue is. I don't understand the above. What is the interval that causes an issue, and what is that issue?

**Comment by chazzmoney** [comment]
In the current system, there is no functional difference between the interval 60 and the interval ‘My. The code paths present in util.get_time_interval are not executed.

**Comment by chazzmoney** [comment]
Per our slack convo, ‘M’ is supposed to aggregate on the clock minute, not every 60 seconds. The existing code will aggregate every 60 seconds even if the config is set to ‘M’. 

Additionally, there were several code paths that failed/were broken once the interval variable was corrected. I believe all character based intervals were being incorrectly processed as being the same as the number of seconds in that interval.
