### ISSUE TITLE
Backfill failed for BITMEX 

### ISSUE THREAD

**Issue by senma3** [bmoscon/cryptostore#73]
hi,
i'm trying to do a backfill of trades from bitmex but today i have checked grafana (i use influxdb) my last trade is in the same day when i started cryptostore
`2020-03-31 15:29:39,687 : ERROR : Backfill failed for BITMEX - XBTUSD
Traceback (most recent call last):
  File "/home/cg/.local/lib/python3.7/site-packages/cryptostore/plugin/backfill.py", line 93, in _worker
    storage.write(exchange, 'trades', pair, end.timestamp())
  File "/home/cg/.local/lib/python3.7/site-packages/cryptostore/data/storage.py", line 37, in write
    s.write(exchange, data_type, pair, timestamp)
  File "/home/cg/.local/lib/python3.7/site-packages/cryptostore/data/influx.py", line 47, in write
    agg.append(f'{data_type}-{exchange},pair={pair},exchange={exchange} side="{entry["side"]}",id="{entry["id"]}",amount={entry["amount"]},price={entry["price"]},timestamp={entry["timestamp"]},receipt_timestamp={entry["receipt_timestamp"]} {ts}')
KeyError: 'receipt_timestamp'`

this is my config:

cache: redis

redis:
    ip: '127.0.0.1'
    port: 6379
    socket: null
    del_after_read: true
    retention_time: null
    start_flush: true

exchanges:
    BITMEX:
        retries: -1
        l2_book:
            symbols: [XBTUSD]
            max_depth: 25
            book_delta: true
            book_interval: 30
        trades: [XBTUSD]
        funding: [XBTUSD]

storage: [influx]

pass_through:
    type: zmq
    host: '127.0.0.1'
    port: 5678

influx:
    host: 'http://127.0.0.1:8086'
    db: tick_data
    create: false

storage_interval: 30

plugins:
    backfill:
        config: config.yaml

backfill:
    BITMEX:
        XBTUSD:
            start: '2017-01-01'`
in my config all is well indented

**Comment by bmoscon** [comment]
ah ok - this is a new issue. Looks like the data from backfill is missing the receipt timestamp, which is irrelevant because its not coming in realtime. I'll try and get this fixed this week.

**Comment by senma3** [comment]
thanks for your quick replay, i wait news

**Comment by bmoscon** [comment]
backfill deprecated/removed. A new version will be released next month, but for now this issue is closed since it no longer applies
