### ISSUE TITLE
Daemonize cryptostore?

### ISSUE THREAD

**Issue by yohplala** [bmoscon/cryptostore#85]
Hi,

I am new to Cryptostore.
I see there is no mention of daemonizing it in its configuration file (so that once started, the user can use the terminal for something else)

Redis has for instance in its configuration file:
`daemonize         yes`

Is it existing as well for Cryptostore?

Thanks for the feedback.
Bests,

**Comment by bmoscon** [comment]
no, it doesnt. it can be added but then you need a lockfile and a way to determine if its running and provide support for restart, stop, start, status, etc. Kind of a lot of work for little gain. You can run it and move it to the background, nohup it, use multiple terminals, etc. I'd take this as a PR but its not something I'm likely to spend time doing as I don't see the value in it.

**Comment by yohplala** [comment]
Ok, thanks,
Closing, there are certainly much more interesting other dev to do.

**Comment by bohuspollak** [comment]
you can run it under the "screen" 
$yum install screen
