### ISSUE TITLE
How retrieveing data still cached in Redis or Kafka when starting a new app?

### ISSUE THREAD

**Issue by yohplala** [bmoscon/cryptostore#86]
Hi,
Let say I am creating parquet file once a week.
So meanwhile, data is cached in Redis or Kafka.

Let say, parallel to data recording, 2 or 3 days after having started cryptostore, I start a 2nd app to which I will pass data as well (for instance a trading bot).
But this 2nd app needs the data still cached in Redis or Kafka, and I don't want to wait till the end of the week that the data being cached is dumped into a parquet file.

So the question: how should I do?
This 2nd app will be python.
Is there a method in cryptostore lib that I can import in my second app to get access to data still in redis or Kafka to retrieve it (without removing it, so that cryptostore can continue recording it in a parquet file)

If not existing, do not hesitate to share how this would have to be implemented.
Not in the short term, but once the GDrive connection is managed, I can try to have a look. 
Thanks for the tip.

**Comment by bmoscon** [comment]
its unlikely you'll be able to store even 1 day of data in redis unless you are using low volume data (or have a ton of memory), but if you are, you can just read the data out of redis? You don't need anything special from cryptostore, there are some solid python redis libraries that will let you read out the data

**Comment by bmoscon** [comment]
thats going to make it quite slow unless you have a specialized machine for running redis, not saying it can't be done, but definitely better for the volume of data if its all in memory
