### ISSUE TITLE
Anchoring storage interval?

### ISSUE THREAD

**Issue by yohplala** [bmoscon/cryptostore#87]
Hi,

storage_interval currently defines an unanchored interval.
Would it be acceptable to make possible use of anchored interval?
For instance, this could be triggered by use of a different time interval string so as not to break current configuration option:
MS: Minute start
HS: Hour start
DS: Day start (midnight)

Thanks for the feedback.
Bests,

**Comment by bmoscon** [comment]
definitely possible, not really a priority for me since nearly any storage medium will allow you to select data by a date range

**Comment by yohplala** [comment]
Yes, I agree. The best option I think (given the work on-going on connectors and more specifically the Google Drive connector) is 'simply' to store last and first timestamps as metadata when recording data, so as to be able to query files according it. When I am done with Google Drive connector v1 as it is, I will see if I can extend it this way.

**Comment by bmoscon** [comment]
actually, this is already done, if you use the letters (1M, 2S, 1H, etc) it will only store data from those intervals

**Comment by bmoscon** [comment]
see https://github.com/bmoscon/cryptostore/issues/56
