### ISSUE TITLE
Creating `store` object (from `Storage` class) only once every `storage_interval`

### ISSUE THREAD

**Issue by yohplala** [bmoscon/cryptostore#89]
Hello,

Currently, a `store` object (from `Storage` class) is created for each `exchange`/`data_type`/`pair`/`storage_interval` by being located [line 88](https://github.com/bmoscon/cryptostore/blob/7b5d1825294ea9bc0b1d8b8c822718860e48f7dc/cryptostore/aggregator/aggregator.py#L88) in `aggregator.py`.

This is kind of rich. I understand that this makes possible to have a 'dynamic' config, i.e. that the user can update the config file, and it will be taken into account at the next iteration, is it right?

If moving the `store` creation few lines above, before loops over `exchange`/`data_type`/`pair`, it would allow to create it only once every `storage_interval`, and it seems to me that the 'dynamic' config is preserved.

Please, do you see any drawback to this?

I am querying this change, because I would like then to 'initialize' the Google Drive connector during creation of the `store` object.

In the `__init__` of the `store` object, and more specifically during the subsequent  `__init__` of the `parquet` object in `parquet.py`, when configuration of the external storage is managed (and more specifically that of the Google Drive connector [here](https://github.com/yohplala/cryptostore/blob/a4ae98680e230a5a532f84209909a3d281cecd02/cryptostore/data/parquet.py#L53))
I would retrieve folder IDs in Google Drive to manage recording of files depending of requested exchange/data_type/pair, and I would integrate this data as a dictionary in kwargs dictionary.

So instead of issuing 3 to 4 http requests per single file to record each `storage_interval`, I would issue:
- 2 or 3 each `storage_interval` (getting `drive` object, querying  folder list, create those missing)
- 1 per file to upload (given its size is below 100MB which I believe it is :))

Do you see any trouble with this proposal?
(this would mean moving creation of the `store` object just prior to [line 81](https://github.com/bmoscon/cryptostore/blob/7b5d1825294ea9bc0b1d8b8c822718860e48f7dc/cryptostore/aggregator/aggregator.py#L81) in `aggregator.py`.

If it is ok for you, I will have a look to implement it.
Thanks for your support!

**Comment by yohplala** [comment]
This ticket is solved in PR #90

**Comment by bmoscon** [comment]
This wont work, this creates a class that aggregates the data for that exchange/symbol pair

**Comment by bmoscon** [comment]
I should also mentioned 2 things:

1. I've been working to make the writes happen in parallel, so another reason this would not work as-is
2. If you want this to happen a few things would need to be done:
  * Any code would need to be threadsafe (i think the google drive code is not based on some docs I saw on the google SDK)
  * Extensive testing - every storage option would need to be tested. 

It seems like a lot of work for little gain, but its up to you!

**Comment by yohplala** [comment]
@bmoscon Hi Bryant, as mention in the PR, I have followed their recommandation to make the implementation threadsafe
For extensive testing, I have tested for several hours GDrive connector. (but I need of course to check with your new design), but I cannot test the other storage option. Is it someting you can have a look?

I will have a look to the change you made in the design and update the PR.
I have tested with several exchanges/data_type/pairs at the same time and did not find any trouble in my testing.
I don't understand the 'This wont work, this creates a class that aggregates the data for that exchange/symbol pair'

In the code I will re-push, if you can spot more exactly where in the code you anticipate a trouble I will then have a look.
Bests,
