### ISSUE TITLE
Make accessible compression capabilities of pyarrow for parquet files

### ISSUE THREAD

**Issue by yohplala** [bmoscon/cryptostore#91]
Hi,
I am preparing a PR for making accessible compression capabilities of pyarrow for parquet files.
I have already made some tests and got quite interesting results.

First off, a general benchmark is available [here](https://quixdb.github.io/squash-benchmark/) for miscellaneous codecs (squash benchmark).

The list of codecs available in pyarrow when using `write_table` is available in [pyarrow documentation](https://arrow.apache.org/docs/python/generated/pyarrow.parquet.write_table.html). They list:
{‘NONE’, ‘SNAPPY’, ‘GZIP’, ‘LZO’, ‘BROTLI’, ‘LZ4’, ‘ZSTD’}

I have tested all of them with a parquet file generated by Cryptostore, and containing a l2 order book.
As written by cryptostore (no compression), its size is 6,2MB.
I have not monitored the added CPU time for each test, and user will have to take care about this.

Results:
- SNAPPY: no change in file size
- GZIP (compression level from 1 to 9),
  - compression level 1: 5,1MB
  - compression level 5: 4,5MB
  - compression level 9: 4,6MB  (the higher is not necessarily the better)
- **BROTLI** (compression level from 1 to 11),
  - compression level 1: 3,2MB
  - **compression level 4: 2,3MB**    <= /!\ jewel here /!\ CPU time needs to be monitored.
  - compression level 8: 2,2MB
  - compression level 11: 1,9MB
- LZO,despite being mentionned in the documentation, an error message indicates that this codec is not available when running it. I opened [a ticket](https://issues.apache.org/jira/browse/ARROW-9636) in pyarrow project.
- LZ4 (compression level from 1 to 12),
  Compression level is actually not available in pyarrow. I opened [another ticket](https://issues.apache.org/jira/browse/ARROW-9648) to inform about this limitation.
  So, the default level is used, which is level 1 according LZ4 man page.
  - compression level 1: 5,2MB
- **ZSTD** (compression level from 1 to 22),
  - compression level 1: 3,1MB
  - **compression level 10: 2,3MB**    <= /!\ jewel here /!\ CPU time needs to be monitored.
  - compression level 22: 2,2MB

I will have a deeper look on compression time, but this quick benchmark shows that gains can be substantial on disk space saving.

I will start also the implementation.
Bests,

**Comment by bmoscon** [comment]
@yohplala this can be closed now, right?

**Comment by yohplala** [comment]
Absolutely! Closing it myself! :)
