### ISSUE TITLE
TypeError: read() got an unexpected keyword argument 'start'

### ISSUE THREAD

**Issue by deus777** [bmoscon/cryptostore#94]
using kafka

File "/home/v/anaconda3/lib/python3.8/site-packages/cryptostore/aggregator/aggregator.py", line 89, in loop
    data = cache.read(exchange, dtype, pair, start=start, end=end)
TypeError: read() got an unexpected keyword argument 'start'

defined in above as
    def read(self, exchange, dtype, pair):

raises exception and dies

**Comment by bmoscon** [comment]
can you confirm the version of cryptostore you are using? can you also post the config?

**Comment by deus777** [comment]
dont know how to get the version, its whatever is in the current repo, I looked at the current source
in
./cryptostore/aggregator/kafka.py

read is defined as 
def read(self, exchange, dtype, pair):

however is called /cryptostore/aggregator/aggregator.py as 
data = cache.read(exchange, dtype, pair, start=start, end=end)

the Redis class defines it correctly with start and end parameters. the Kafka class cause an exception and terminates program
I switched to Redis as aworkaround

**Comment by bmoscon** [comment]
fixed - thanks for raising
